//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExceptionLog
    {
        public long LogId { get; set; }
        public string Exceptionmsg { get; set; }
        public string Exceptiontype { get; set; }
        public string Exceptionsource { get; set; }
        public string ExceptionURL { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
