//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Async_Controller_Prj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int empid { get; set; }
        public string empname { get; set; }
        public string gender { get; set; }
        public Nullable<double> salary { get; set; }
        public Nullable<int> deptid { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
