//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceClient.infinite_reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="infinite_reference.WebinfiniteseviceSoap")]
    public interface WebinfiniteseviceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServiceClient.infinite_reference.HelloWorldResponse HelloWorld(WebServiceClient.infinite_reference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.infinite_reference.HelloWorldResponse> HelloWorldAsync(WebServiceClient.infinite_reference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/greeting", ReplyAction="*")]
        WebServiceClient.infinite_reference.greetingResponse greeting(WebServiceClient.infinite_reference.greetingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/greeting", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.infinite_reference.greetingResponse> greetingAsync(WebServiceClient.infinite_reference.greetingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/squarroot", ReplyAction="*")]
        float squarroot(float f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/squarroot", ReplyAction="*")]
        System.Threading.Tasks.Task<float> squarrootAsync(float f);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.infinite_reference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServiceClient.infinite_reference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.infinite_reference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServiceClient.infinite_reference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class greetingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="greeting", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.infinite_reference.greetingRequestBody Body;
        
        public greetingRequest() {
        }
        
        public greetingRequest(WebServiceClient.infinite_reference.greetingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class greetingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public greetingRequestBody() {
        }
        
        public greetingRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class greetingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="greetingResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.infinite_reference.greetingResponseBody Body;
        
        public greetingResponse() {
        }
        
        public greetingResponse(WebServiceClient.infinite_reference.greetingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class greetingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string greetingResult;
        
        public greetingResponseBody() {
        }
        
        public greetingResponseBody(string greetingResult) {
            this.greetingResult = greetingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebinfiniteseviceSoapChannel : WebServiceClient.infinite_reference.WebinfiniteseviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebinfiniteseviceSoapClient : System.ServiceModel.ClientBase<WebServiceClient.infinite_reference.WebinfiniteseviceSoap>, WebServiceClient.infinite_reference.WebinfiniteseviceSoap {
        
        public WebinfiniteseviceSoapClient() {
        }
        
        public WebinfiniteseviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebinfiniteseviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebinfiniteseviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebinfiniteseviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.infinite_reference.HelloWorldResponse WebServiceClient.infinite_reference.WebinfiniteseviceSoap.HelloWorld(WebServiceClient.infinite_reference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServiceClient.infinite_reference.HelloWorldRequest inValue = new WebServiceClient.infinite_reference.HelloWorldRequest();
            inValue.Body = new WebServiceClient.infinite_reference.HelloWorldRequestBody();
            WebServiceClient.infinite_reference.HelloWorldResponse retVal = ((WebServiceClient.infinite_reference.WebinfiniteseviceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.infinite_reference.HelloWorldResponse> WebServiceClient.infinite_reference.WebinfiniteseviceSoap.HelloWorldAsync(WebServiceClient.infinite_reference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.infinite_reference.HelloWorldResponse> HelloWorldAsync() {
            WebServiceClient.infinite_reference.HelloWorldRequest inValue = new WebServiceClient.infinite_reference.HelloWorldRequest();
            inValue.Body = new WebServiceClient.infinite_reference.HelloWorldRequestBody();
            return ((WebServiceClient.infinite_reference.WebinfiniteseviceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.infinite_reference.greetingResponse WebServiceClient.infinite_reference.WebinfiniteseviceSoap.greeting(WebServiceClient.infinite_reference.greetingRequest request) {
            return base.Channel.greeting(request);
        }
        
        public string greeting(string username) {
            WebServiceClient.infinite_reference.greetingRequest inValue = new WebServiceClient.infinite_reference.greetingRequest();
            inValue.Body = new WebServiceClient.infinite_reference.greetingRequestBody();
            inValue.Body.username = username;
            WebServiceClient.infinite_reference.greetingResponse retVal = ((WebServiceClient.infinite_reference.WebinfiniteseviceSoap)(this)).greeting(inValue);
            return retVal.Body.greetingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.infinite_reference.greetingResponse> WebServiceClient.infinite_reference.WebinfiniteseviceSoap.greetingAsync(WebServiceClient.infinite_reference.greetingRequest request) {
            return base.Channel.greetingAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.infinite_reference.greetingResponse> greetingAsync(string username) {
            WebServiceClient.infinite_reference.greetingRequest inValue = new WebServiceClient.infinite_reference.greetingRequest();
            inValue.Body = new WebServiceClient.infinite_reference.greetingRequestBody();
            inValue.Body.username = username;
            return ((WebServiceClient.infinite_reference.WebinfiniteseviceSoap)(this)).greetingAsync(inValue);
        }
        
        public float squarroot(float f) {
            return base.Channel.squarroot(f);
        }
        
        public System.Threading.Tasks.Task<float> squarrootAsync(float f) {
            return base.Channel.squarrootAsync(f);
        }
    }
}
