// <auto-generated />
namespace Ajax_posting_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Studentmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Studentmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202601120635460_Studentmigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
